[env]
platform = atmelavr
board = megaatmega2560
framework = arduino

[env:megaatmega2560]
lib_deps = 
    MotorPresets
    AccelStepper

build_flags = 
    -D MOTOR_PRESETS_ENABLED

monitor_speed = 115200

[platformio]
src_dir = src
lib_dir = lib
include_dir = include
test_dir = test
extra_scripts = pre:extra_script.py