[env]
platform = atmelavr
board = uno
framework = arduino

[env:uno]
lib_deps = 
    AccelStepper
    # Add any other libraries you may need here

build_flags = 
    -D NBMOTEURS=10
    -D NBDATA=34
    -D NBPASPARTOUR=3200

upload_port = /dev/ttyUSB0  ; Change this to your actual port
monitor_speed = 115200